/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c1c7d4",
        "primary": "#005fad",
        "primary-container": "#4895ef",
        "on-primary": "#ffffff",
        "on-primary-container": "#002c55",
        "secondary": "#396093",
        "secondary-container": "#a0c6ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#2a5284",
        "tertiary": "#006780",
        "tertiary-container": "#00a0c5",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9fa",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#414752",
        "outline": "#717783",
        "background": "#f8f9fa",
        "error": "#ba1a1a",
        "inverse-primary": "#a4c9ff",
        "inverse-surface": "#2e3132",
        "surface-tint": "#005fad",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "primary-fixed": "#d4e3ff",
        "secondary-fixed": "#d4e3ff",
        "tertiary-fixed": "#b7eaff",
        "tertiary-fixed-dim": "#5bd5fc",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
